<a href="https://colab.research.google.com/github/Nesraik/Scientific-Computing-LAB-/blob/main/Session%201/Session_1_Variable_%26_Assignment%2C_Data_type_%26_Numpy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import time
print(time.ctime())

Sat Mar 11 03:23:03 2023


In [ ]:
x = 1
x = x + 1
x

2

In [ ]:
x = 1
y = x + 1
x = 2
y

2

In [ ]:
import numpy as np

x = np.array ([1,4,3])
print(x)
print("\n")
y = np.array([[1,4,3],[9,2,7]])
print(y)

[1 4 3]


[[1 4 3]
 [9 2 7]]
